import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1786562451919 implements MigrationInterface {
    name = 'InitialSchema1786562451919'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "functions" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "slug" character varying NOT NULL, "description" text, CONSTRAINT "UQ_c95f162e472ae185ee2781b4df4" UNIQUE ("slug"), CONSTRAINT "PK_203889d2ae5a98ffc137739301e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "certifications" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "iconUrl" character varying, CONSTRAINT "UQ_9eb29158fdc27b227a71c7f138c" UNIQUE ("name"), CONSTRAINT "PK_fd763d412e4a1fb1b6dadd6e72b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."product_variants_stockstatus_enum" AS ENUM('IN_STOCK', 'LOW_STOCK', 'OUT_OF_STOCK', 'BACKORDER')`);
        await queryRunner.query(`CREATE TABLE "product_variants" ("id" SERIAL NOT NULL, "productId" integer NOT NULL, "sku" character varying NOT NULL, "label" character varying NOT NULL, "price" numeric(10,2) NOT NULL, "salePrice" numeric(10,2), "saleStart" TIMESTAMP WITH TIME ZONE, "saleEnd" TIMESTAMP WITH TIME ZONE, "stockQuantity" integer, "stockStatus" "public"."product_variants_stockstatus_enum" NOT NULL DEFAULT 'IN_STOCK', "imageUrl" character varying, "moq" integer, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_46f236f21640f9da218a063a866" UNIQUE ("sku"), CONSTRAINT "PK_281e3f2c55652d6a22c0aa59fd7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_images" ("id" SERIAL NOT NULL, "productId" integer NOT NULL, "url" character varying NOT NULL, "altText" character varying, "sortOrder" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_1974264ea7265989af8392f63a1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."product_documents_type_enum" AS ENUM('COA', 'SDS', 'TDS', 'SPEC_SHEET', 'OTHER')`);
        await queryRunner.query(`CREATE TABLE "product_documents" ("id" SERIAL NOT NULL, "productId" integer NOT NULL, "type" "public"."product_documents_type_enum" NOT NULL, "url" character varying NOT NULL, "label" character varying, CONSTRAINT "PK_007c014bf4a96e835c9ebac2eab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_specs" ("id" SERIAL NOT NULL, "productId" integer NOT NULL, "key" character varying NOT NULL, "value" character varying NOT NULL, CONSTRAINT "PK_d0cb5ab51b09cdbb6d3e6ce50f5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "products" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "slug" character varying NOT NULL, "sku" character varying NOT NULL, "inciName" character varying, "botanicalName" character varying, "casNumber" character varying, "shortDescription" text, "chemicalDescriptions" text, "imageUrl" character varying, "categoryId" integer NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "isFeatured" boolean NOT NULL DEFAULT false, "metaTitle" character varying, "metaDescription" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_464f927ae360106b783ed0b4106" UNIQUE ("slug"), CONSTRAINT "UQ_c44ac33a05b144dd0d9ddcf9327" UNIQUE ("sku"), CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_464f927ae360106b783ed0b410" ON "products" ("slug") `);
        await queryRunner.query(`CREATE TABLE "categories" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "slug" character varying NOT NULL, "description" text, "imageUrl" character varying, "parentId" integer, "sortOrder" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_420d9f679d41281f282f5bc7d09" UNIQUE ("slug"), CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "quote_request_items" ("id" SERIAL NOT NULL, "quoteRequestId" integer NOT NULL, "productId" integer, "productName" character varying NOT NULL, "quantity" integer, "unit" character varying, "notes" text, CONSTRAINT "PK_acc856887c8eb96467419db08c5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."quote_requests_type_enum" AS ENUM('QUOTE', 'SAMPLE', 'WHITE_LABEL', 'CONTACT')`);
        await queryRunner.query(`CREATE TYPE "public"."quote_requests_status_enum" AS ENUM('NEW', 'IN_PROGRESS', 'QUOTED', 'WON', 'LOST')`);
        await queryRunner.query(`CREATE TABLE "quote_requests" ("id" SERIAL NOT NULL, "companyId" integer, "userId" integer, "fullName" character varying NOT NULL, "email" character varying NOT NULL, "phone" character varying, "companyName" character varying, "message" text, "type" "public"."quote_requests_type_enum" NOT NULL DEFAULT 'QUOTE', "status" "public"."quote_requests_status_enum" NOT NULL DEFAULT 'NEW', "assignedToId" integer, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c05f72de8be0ec6b0985a851558" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."cart_items_purchasetype_enum" AS ENUM('one-time', 'subscription')`);
        await queryRunner.query(`CREATE TABLE "cart_items" ("id" SERIAL NOT NULL, "cartId" integer NOT NULL, "productVariantId" integer NOT NULL, "quantity" integer NOT NULL DEFAULT '1', "price" numeric(10,2) NOT NULL, "regularPrice" numeric(10,2), "purchaseType" "public"."cart_items_purchasetype_enum" NOT NULL DEFAULT 'one-time', "subscriptionFrequencyMonths" integer, "subscriptionDiscountPercent" numeric(5,2), CONSTRAINT "PK_6fccf5ec03c172d27a28a82928b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "carts" ("id" SERIAL NOT NULL, "userId" integer NOT NULL, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_69828a178f152f157dcf2f70a89" UNIQUE ("userId"), CONSTRAINT "REL_69828a178f152f157dcf2f70a8" UNIQUE ("userId"), CONSTRAINT "PK_b5f695a59f5ebb50af3c8160816" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."order_items_purchasetype_enum" AS ENUM('one-time', 'subscription')`);
        await queryRunner.query(`CREATE TABLE "order_items" ("id" SERIAL NOT NULL, "orderId" integer NOT NULL, "productVariantId" integer NOT NULL, "productName" character varying NOT NULL, "variantLabel" character varying NOT NULL, "sku" character varying NOT NULL, "quantity" integer NOT NULL, "price" numeric(10,2) NOT NULL, "purchaseType" "public"."order_items_purchasetype_enum" NOT NULL DEFAULT 'one-time', CONSTRAINT "PK_005269d8574e6fac0493715c308" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."orders_status_enum" AS ENUM('PENDING', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "orders" ("id" SERIAL NOT NULL, "userId" integer NOT NULL, "status" "public"."orders_status_enum" NOT NULL DEFAULT 'PENDING', "subtotal" numeric(12,2) NOT NULL, "total" numeric(12,2) NOT NULL, "shippingAddress" text, "notes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('CUSTOMER', 'ADMIN', 'SALES')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" SERIAL NOT NULL, "email" character varying NOT NULL, "passwordHash" character varying, "fullName" character varying NOT NULL, "phone" character varying, "role" "public"."users_role_enum" NOT NULL DEFAULT 'CUSTOMER', "companyId" integer, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."companies_status_enum" AS ENUM('PENDING', 'APPROVED', 'REJECTED', 'SUSPENDED')`);
        await queryRunner.query(`CREATE TABLE "companies" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "taxId" character varying, "website" character varying, "industry" character varying, "status" "public"."companies_status_enum" NOT NULL DEFAULT 'PENDING', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d4bc3e82a314fa9e29f652c2c22" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "testimonials" ("id" SERIAL NOT NULL, "authorName" character varying NOT NULL, "company" character varying, "quote" text NOT NULL, "result" character varying, "imageUrl" character varying, "isPublished" boolean NOT NULL DEFAULT true, "sortOrder" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_63b03c608bd258f115a0a4a1060" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "newsletter_subscribers" ("id" SERIAL NOT NULL, "email" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_0dc48416511f011f7de7b2a8f83" UNIQUE ("email"), CONSTRAINT "PK_38f9333e9961b2fdb589128d19b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "seo_pages" ("id" SERIAL NOT NULL, "path" character varying NOT NULL, "metaTitle" character varying, "metaDescription" text, "ogImageUrl" character varying, CONSTRAINT "UQ_bacd670727e5596350249c4e286" UNIQUE ("path"), CONSTRAINT "PK_2aeda7654601ab4fb8fdaa32a51" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_functions" ("productId" integer NOT NULL, "functionId" integer NOT NULL, CONSTRAINT "PK_132af6df107d99ec9725cf0e41b" PRIMARY KEY ("productId", "functionId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_dd0f24770b665645f3273c5440" ON "product_functions" ("productId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b8c9a1dab8df6cd7c50adf0ac9" ON "product_functions" ("functionId") `);
        await queryRunner.query(`CREATE TABLE "product_certifications" ("productId" integer NOT NULL, "certificationId" integer NOT NULL, CONSTRAINT "PK_96ff55af1f287f62c209413d392" PRIMARY KEY ("productId", "certificationId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cf5e973cf15a3049049d9284e4" ON "product_certifications" ("productId") `);
        await queryRunner.query(`CREATE INDEX "IDX_61d4ebfd0ea444d72dbd7c04ec" ON "product_certifications" ("certificationId") `);
        await queryRunner.query(`ALTER TABLE "product_variants" ADD CONSTRAINT "FK_f515690c571a03400a9876600b5" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_images" ADD CONSTRAINT "FK_b367708bf720c8dd62fc6833161" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_documents" ADD CONSTRAINT "FK_31525dcd129d1735732343fe664" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_specs" ADD CONSTRAINT "FK_2831fa1ffe991b72d1e38f2f625" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_ff56834e735fa78a15d0cf21926" FOREIGN KEY ("categoryId") REFERENCES "categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "categories" ADD CONSTRAINT "FK_9a6f051e66982b5f0318981bcaa" FOREIGN KEY ("parentId") REFERENCES "categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quote_request_items" ADD CONSTRAINT "FK_7ee2a72bad32b1298c376894fb5" FOREIGN KEY ("quoteRequestId") REFERENCES "quote_requests"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quote_requests" ADD CONSTRAINT "FK_722a601ebdf44c945429ea62485" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quote_requests" ADD CONSTRAINT "FK_1ea22edc0dff28ac7d12e446f73" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD CONSTRAINT "FK_edd714311619a5ad09525045838" FOREIGN KEY ("cartId") REFERENCES "carts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD CONSTRAINT "FK_98ba4bbf6e3611d2062b898f5c1" FOREIGN KEY ("productVariantId") REFERENCES "product_variants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "carts" ADD CONSTRAINT "FK_69828a178f152f157dcf2f70a89" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_f1d359a55923bb45b057fbdab0d" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_9cf6578d9f8c7f43cc96c7af6d8" FOREIGN KEY ("productVariantId") REFERENCES "product_variants"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_151b79a83ba240b0cb31b2302d1" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_6f9395c9037632a31107c8a9e58" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_functions" ADD CONSTRAINT "FK_dd0f24770b665645f3273c5440a" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "product_functions" ADD CONSTRAINT "FK_b8c9a1dab8df6cd7c50adf0ac9b" FOREIGN KEY ("functionId") REFERENCES "functions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_certifications" ADD CONSTRAINT "FK_cf5e973cf15a3049049d9284e40" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "product_certifications" ADD CONSTRAINT "FK_61d4ebfd0ea444d72dbd7c04ec1" FOREIGN KEY ("certificationId") REFERENCES "certifications"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "product_certifications" DROP CONSTRAINT "FK_61d4ebfd0ea444d72dbd7c04ec1"`);
        await queryRunner.query(`ALTER TABLE "product_certifications" DROP CONSTRAINT "FK_cf5e973cf15a3049049d9284e40"`);
        await queryRunner.query(`ALTER TABLE "product_functions" DROP CONSTRAINT "FK_b8c9a1dab8df6cd7c50adf0ac9b"`);
        await queryRunner.query(`ALTER TABLE "product_functions" DROP CONSTRAINT "FK_dd0f24770b665645f3273c5440a"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_6f9395c9037632a31107c8a9e58"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_151b79a83ba240b0cb31b2302d1"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_9cf6578d9f8c7f43cc96c7af6d8"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_f1d359a55923bb45b057fbdab0d"`);
        await queryRunner.query(`ALTER TABLE "carts" DROP CONSTRAINT "FK_69828a178f152f157dcf2f70a89"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP CONSTRAINT "FK_98ba4bbf6e3611d2062b898f5c1"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP CONSTRAINT "FK_edd714311619a5ad09525045838"`);
        await queryRunner.query(`ALTER TABLE "quote_requests" DROP CONSTRAINT "FK_1ea22edc0dff28ac7d12e446f73"`);
        await queryRunner.query(`ALTER TABLE "quote_requests" DROP CONSTRAINT "FK_722a601ebdf44c945429ea62485"`);
        await queryRunner.query(`ALTER TABLE "quote_request_items" DROP CONSTRAINT "FK_7ee2a72bad32b1298c376894fb5"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP CONSTRAINT "FK_9a6f051e66982b5f0318981bcaa"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_ff56834e735fa78a15d0cf21926"`);
        await queryRunner.query(`ALTER TABLE "product_specs" DROP CONSTRAINT "FK_2831fa1ffe991b72d1e38f2f625"`);
        await queryRunner.query(`ALTER TABLE "product_documents" DROP CONSTRAINT "FK_31525dcd129d1735732343fe664"`);
        await queryRunner.query(`ALTER TABLE "product_images" DROP CONSTRAINT "FK_b367708bf720c8dd62fc6833161"`);
        await queryRunner.query(`ALTER TABLE "product_variants" DROP CONSTRAINT "FK_f515690c571a03400a9876600b5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_61d4ebfd0ea444d72dbd7c04ec"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cf5e973cf15a3049049d9284e4"`);
        await queryRunner.query(`DROP TABLE "product_certifications"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b8c9a1dab8df6cd7c50adf0ac9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dd0f24770b665645f3273c5440"`);
        await queryRunner.query(`DROP TABLE "product_functions"`);
        await queryRunner.query(`DROP TABLE "seo_pages"`);
        await queryRunner.query(`DROP TABLE "newsletter_subscribers"`);
        await queryRunner.query(`DROP TABLE "testimonials"`);
        await queryRunner.query(`DROP TABLE "companies"`);
        await queryRunner.query(`DROP TYPE "public"."companies_status_enum"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`DROP TYPE "public"."orders_status_enum"`);
        await queryRunner.query(`DROP TABLE "order_items"`);
        await queryRunner.query(`DROP TYPE "public"."order_items_purchasetype_enum"`);
        await queryRunner.query(`DROP TABLE "carts"`);
        await queryRunner.query(`DROP TABLE "cart_items"`);
        await queryRunner.query(`DROP TYPE "public"."cart_items_purchasetype_enum"`);
        await queryRunner.query(`DROP TABLE "quote_requests"`);
        await queryRunner.query(`DROP TYPE "public"."quote_requests_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."quote_requests_type_enum"`);
        await queryRunner.query(`DROP TABLE "quote_request_items"`);
        await queryRunner.query(`DROP TABLE "categories"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_464f927ae360106b783ed0b410"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP TABLE "product_specs"`);
        await queryRunner.query(`DROP TABLE "product_documents"`);
        await queryRunner.query(`DROP TYPE "public"."product_documents_type_enum"`);
        await queryRunner.query(`DROP TABLE "product_images"`);
        await queryRunner.query(`DROP TABLE "product_variants"`);
        await queryRunner.query(`DROP TYPE "public"."product_variants_stockstatus_enum"`);
        await queryRunner.query(`DROP TABLE "certifications"`);
        await queryRunner.query(`DROP TABLE "functions"`);
    }

}
