import 'reflect-metadata';
import * as dotenv from 'dotenv';
import { DataSource } from 'typeorm';

dotenv.config();
import {
  Category,
  Function,
  Certification,
  Product,
  ProductVariant,
  ProductImage,
  ProductDocument,
  ProductSpec,
  ProductSeo,
  Company,
  User,
  RefreshToken,
  PasswordResetRequest,
  Cart,
  CartItem,
  Order,
  OrderItem,
  QuoteRequest,
  QuoteRequestItem,
  Testimonial,
  NewsletterSubscriber,
  SeoPage,
  ContactMessage,
  Coupon,
  CouponUsage,
  BulkSaleDiscount,
  SiteSetting,
  SeoMetric,
  SeoIssue,
} from './entities';

export const AppDataSource = new DataSource({
  type: 'postgres',
  host: process.env.DB_HOST || 'localhost',
  port: Number(process.env.DB_PORT) || 5432,
  username: process.env.DB_USER || 'postgres',
  password: process.env.DB_PASSWORD || 'postgres',
  database: process.env.DB_NAME || 'cocojojochem',
  synchronize: false,
  logging: ['error', 'warn'],
  entities: [
    Category,
    Function,
    Certification,
    Product,
    ProductVariant,
    ProductImage,
    ProductDocument,
    ProductSpec,
    ProductSeo,
    Company,
    User,
    RefreshToken,
    PasswordResetRequest,
    Cart,
    CartItem,
    Order,
    OrderItem,
    QuoteRequest,
    QuoteRequestItem,
    Testimonial,
    NewsletterSubscriber,
    SeoPage,
    ContactMessage,
    Coupon,
    CouponUsage,
    BulkSaleDiscount,
    SiteSetting,
    SeoMetric,
    SeoIssue,
  ],
  migrations: ['src/migrations/*.ts'],
});
